export const LOGIN_PROCESS = "LOG_PROCESS"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS ";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SIGNUP_PROCESS = "SIGNUP_PROCESS";
export const SIGNUP_SUCCESS = "SINGUP_SUCCESS"
export const SIGNUP_ERROR = "SINGUP_ERROR"

export const LOG_OUT = "LOG_OUT";
export const GETUSER_PROCESS = "GETUSER_PROCESS";
export const GETUSER_SUCCESS = "GETUSER_SUCCESS";
export const GETUSER_ERROR = "GETUSER_ERROR";