// AUTH TYPES
export const AUTH_LOADING = "LOADING_PROCESS";
export const AUTH_ERROR = "PROCESS_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS ";
export const SIGNUP_SUCCESS = "SINGUP_SUCCESS";
export const GETUSER_SUCCESS = "GETUSER_SUCCESS";

export const LOG_OUT = "LOG_OUT";

//CHALLENGES TYPES
export const GETONECHALLENGE_SUCCESS = "GETONECHALLENGE_SUCCESS";
export const GETCHALLENGES_SUCCESS = "GET_CHALLENGES";
export const CHALLENGES_LOADING = "CHALLENGES_LOADING";
export const CHALLENGES_ERROR = "CHALLENGES_ERROR";